kind: List
apiVersion: v1
items:

- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: rhel7-weblogic
    name: rhel7-weblogic
  spec: {}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: rhel7-weblogic
    name: rhel7-weblogic
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rhel7-weblogic:v12.2.1
    source:
      type: Git
      git:
        uri: https://github.com/rbaumgar/OracleWebLogic.git
      contextDir: 12.2.1
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: rhel7-oraclejdk:latest
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
